# [作業目標]
- 仿造範例的 One Hot Encoding, 將指定的資料進行編碼

# [作業重點]
- 將 sub_train 進行 One Hot Encoding 編碼 (In[4], Out[4])

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
app_train = pd.read_csv('application_train.csv')

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [41]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [45]:
sub_train = pd.get_dummies(sub_train)
sub_train = sub_train.reindex(columns=['WEEKDAY_APPR_PROCESS_START_MONDAY','WEEKDAY_APPR_PROCESS_START_TUESDAY','WEEKDAY_APPR_PROCESS_START_WEDNESDAY','WEEKDAY_APPR_PROCESS_START_THURSDAY','WEEKDAY_APPR_PROCESS_START_FRIDAY','WEEKDAY_APPR_PROCESS_START_SATURDAY','WEEKDAY_APPR_PROCESS_START_SUNDAY'])
print(sub_train.shape)
sub_train.head(20)

(307511, 7)

,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY
0,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0
2,1,0,0,0,0,0,0
3,0,0,1,0,0,0,0
4,0,0,0,1,0,0,0
5,0,0,1,0,0,0,0
6,0,0,0,0,0,0,1
7,1,0,0,0,0,0,0
8,0,0,1,0,0,0,0
9,0,0,0,1,0,0,0
10,0,0,0,0,0,1,0
11,0,0,0,0,1,0,0
12,0,0,0,0,1,0,0
13,0,0,0,1,0,0,0
14,1,0,0,0,0,0,0
15,0,0,0,0,0,1,0
16,0,0,0,1,0,0,0
17,1,0,0,0,0,0,0
18,0,0,0,0,1,0,0
19,1,0,0,0,0,0,0